/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import javax.swing.*; 
import java.awt.*;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;

import java.util.ArrayList;
import model.PersonList;
import model.Person;
import model.User;


/**
 *
 * @author freax
 */
public class MainJFrame extends javax.swing.JFrame {

    private PersonList personList;
    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() { 
        
//        LoginJPanel login = new LoginJPanel();
        initComponents();
        Person person1 = new Person("Person1", "NUID1");
        User user1 = new User("user1", "0b14d501a594442a01c6859541bcb3e8164d183d32937b851835442f69d5c94e", new ArrayList<>(), true, "user");
        user1.getPwds().add("0b14d501a594442a01c6859541bcb3e8164d183d32937b851835442f69d5c94e");
        User user2 = new User("user2", "6cf615d5bcaac778352a8f1f3360d23f02f34ec182e259897fd6ce485d7870d4", new ArrayList<>(), true, "user");
        user2.getPwds().add("6cf615d5bcaac778352a8f1f3360d23f02f34ec182e259897fd6ce485d7870d4");
        person1.addUser(user1);
        person1.addUser(user2);

        Person person0 = new Person("Person0", "   ");
        User user0 = new User("user0", "0b14d501a594442a01c6859541bcb3e8164d183d32937b851835442f69d5c94e", new ArrayList<>(), true, "admin");
        user0.getPwds().add("0b14d501a594442a01c6859541bcb3e8164d183d32937b851835442f69d5c94e");
        person0.addUser(user0);
        
        Person person2 = new Person("Person2", "NUID2");
        User user3 = new User("user3", "5906ac361a137e2d286465cd6588ebb5ac3f5ae955001100bc41577c3d751764", new ArrayList<>(), false, "user");
        user3.getPwds().add("5906ac361a137e2d286465cd6588ebb5ac3f5ae955001100bc41577c3d751764");
        person2.addUser(user3);

        PersonList savepersonList = new PersonList();
        savepersonList.addPerson(person0);
        savepersonList.addPerson(person1);
        savepersonList.addPerson(person2);

        // 将数据写入文件
        writeDataToFile(savepersonList, "personlist.txt");

        // 从文件中读取数据
        PersonList personList = readDataFromFile("personlist.txt");
        
        txtHi.setText("Please Login in");
        btnLogout.setVisible(false);
        LoginJPanel panel = new LoginJPanel(ViewContainer,personList,txtHi,btnLogout);
        ViewContainer.add("LoginJPanel",panel);
        CardLayout layout = (CardLayout)ViewContainer.getLayout();
        layout.next(ViewContainer);
//        jSplitPane1.setRightComponent(login);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        controlPanel = new javax.swing.JPanel();
        txtHi = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        ViewContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtHi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtHi.setText("Hi, ");

        btnLogout.setText("Log out");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(controlPanelLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(txtHi, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(controlPanelLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(btnLogout)))
                .addGap(0, 32, Short.MAX_VALUE))
        );
        controlPanelLayout.setVerticalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlPanelLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(txtHi, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 210, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addGap(205, 205, 205))
        );

        jSplitPane1.setLeftComponent(controlPanel);

        ViewContainer.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(ViewContainer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 892, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        this.personList = readDataFromFile("personlist.txt");
        LoginJPanel panel = new LoginJPanel(ViewContainer,personList,txtHi,btnLogout);
        ViewContainer.add("LoginJPanel",panel);
        CardLayout layout = (CardLayout)ViewContainer.getLayout();
        layout.next(ViewContainer);        // TODO add your handling code here:
        btnLogout.setVisible(false);
       
    }//GEN-LAST:event_btnLogoutActionPerformed
    public static void writeDataToFile(PersonList personList, String filename) {
        try (BufferedWriter writer = new BufferedWriter(new FileWriter(filename))) {
            writer.write(personList.toText());
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

 public static PersonList readDataFromFile(String filename) {
    PersonList personList = new PersonList();
    try (BufferedReader reader = new BufferedReader(new FileReader(filename))) {
        String line;
        Person currentPerson = null;
        User currentUser = null;
        boolean readingPwds = false; // 用于标识是否正在读取密码列表

        while ((line = reader.readLine()) != null) {
            if (line.startsWith("name:")) {
                currentPerson = new Person(line.substring(5), "");
                personList.addPerson(currentPerson);
            } else if (line.startsWith("NUID:")) {
                if (currentPerson != null) {
                    currentPerson.setNUID(line.substring(5));
                }
            } else if (line.startsWith("username:")) {
                currentUser = new User("", "", new ArrayList<>(), false, "");
                if (currentPerson != null) {
                    currentPerson.addUser(currentUser);
                    currentUser.setUsername(line.substring(9));
                }
            } else if (line.startsWith("nowpwd:")) {
                if (currentUser != null) {
                    currentUser.setNowpwd(line.substring(7));
                }
            } else if (line.startsWith("pwds:")) {
                if (currentUser != null) {
                    currentUser.getPwds().add(line.substring(5)); 
                    readingPwds = true; 
                }
            } else if (line.startsWith("pwdsend:")) {
                if (currentUser != null ) { 
                    readingPwds = false;
                }
            } else if (line.startsWith("enabled:")) {
                if (currentUser != null ) { 
                    currentUser.setEnabled(Boolean.parseBoolean(line.substring(8)));
                }
            } else if (line.startsWith("role:")) {
                if (currentUser != null) {
                    currentUser.setRole(line.substring(5));
                }
            } else if (line.isEmpty() && readingPwds) { 
                readingPwds = false;
            }
        }
    } catch (IOException e) {
        e.printStackTrace();
    }
    return personList;
}

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new MainJFrame().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ViewContainer;
    private javax.swing.JButton btnLogout;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel txtHi;
    // End of variables declaration//GEN-END:variables
}
