package ui.UserInterface.WorkAreas.FacultyRole.ManageCourses;

import Business.Course.Course;
import Business.Course.CourseDirectory;
import Business.Course.CourseTopic;
import Business.Course.CourseVO;
import Business.Person.Professor;
import Business.Semester.Semester;
import Tools.MySQLConnectionUtil;

import java.sql.Connection;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author zhangjinming
 */
public class FacultyManageCoursesJPanel extends javax.swing.JPanel {

    /**
     * Creates new form FacultyManageCoursesJPanel
     */
    private JPanel ViewContainer;
    private Professor professor;
    private String thisterm;

    private CourseDirectory courseDirectory ;
//
    private List<Semester> semesters;
    Connection connection;
    Course addCourse;

    List<CourseVO>  professsorCourseList;
    public FacultyManageCoursesJPanel(JPanel ViewContainer, Professor professor){
        connection = MySQLConnectionUtil.getConnection();
        courseDirectory = new CourseDirectory(connection);//数据传到了courseList
        initComponents();
        this.ViewContainer = ViewContainer;
        this.professor = professor;

        this.thisterm="Fall 2023";
        try {
            semesters = Semester.getAllSemestersFromDatabase(connection);
        } catch (SQLException e) {
            e.printStackTrace();
            System.out.println("数据库异常！！");
        }
//        Semester sem=null;
        for(Semester s: semesters){
//            if(s.getSemesterName().equals(thisterm)){
//                sem = s;
//            }
            selectSemComboBox.addItem(s.getSemesterName());
        }

//        getEnrolledCourses("",thisterm);
////        getHistoryCourses(null);
//
        populateTable(thisterm);
////        historyTable();

        tblCurrentCourses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int row = tblCurrentCourses.getSelectedRow(); // 获取所点选行的索引
                DefaultTableModel model = (DefaultTableModel) tblCurrentCourses.getModel(); //Have the access to the table;

                //时间格式转化为String
                DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");



                if(row != -1) { // 如果行已被选择

                    Object id = model.getValueAt(row, 0); // 获取所选行的第1列值

                    for (CourseVO courseVO:professsorCourseList){
                        if (courseVO.getId().equals((String)id)){
//                            selectedCourse = courseVO;
                            txtCurrentCourseId.setText(courseVO.getId());
                            txtCurrentCourseName.setText(courseVO.getName());
                            txtCurrentCourseTopic.setText(courseVO.getTopics().toString());
                            txtCurrentSemester.setText(courseVO.getSemester());
                            txtCurrentCoursePoint.setText(courseVO.getPoint() + "");

                            txtCurrentCourseLocation.setText(courseVO.getLocation());
                            currentCourseIntroductionTextArea.setText(courseVO.getIntroduction());
                            txtCurrentStudentLimited.setText(courseVO.getStudentLimit() + "");
                            txtCurrentStudentCount.setText(courseVO.getStudentCount() + "");
                            txtCurrentCoursePoint.setText(courseVO.getPoint() + "");
//                            txtCurrentCourseStartTime.setText(courseVO.getBeginTime().format(formatter));
//                            txtCurrentCourseEndTime.setText(courseVO.getEndTime().format(formatter));

                        }
                    }
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainTabbedPane = new javax.swing.JTabbedPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        currentCourseScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        tblCurrentCourses1 = new javax.swing.JTable();
        txtCurrentCourseId1 = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        txtCurrentCourseTopic1 = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        txtCurrentCourseName1 = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        txtCurrentCoursePoint1 = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        txtCurrentSemester1 = new javax.swing.JTextField();
        txtCurrentCourseLocation1 = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        lblCourseEndTime3 = new javax.swing.JLabel();
        lblStudentLimited3 = new javax.swing.JLabel();
        txtCurrentStudentLimited1 = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        txtCurrentStudentCount1 = new javax.swing.JTextField();
        btnSaveCurrentCourse1 = new javax.swing.JButton();
        jLabel48 = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        currentCourseIntroductionTextArea1 = new javax.swing.JTextArea();
        cbBeginHour2 = new javax.swing.JComboBox<>();
        cbBeginMinute2 = new javax.swing.JComboBox<>();
        cbEndHour2 = new javax.swing.JComboBox<>();
        cbEndMinute2 = new javax.swing.JComboBox<>();
        jLabel49 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblStudent2 = new javax.swing.JTable();
        txtSearchStudent2 = new javax.swing.JTextField();
        btnSearchStudent2 = new javax.swing.JButton();
        jLabel50 = new javax.swing.JLabel();
        txtStudentName2 = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        txtStudentId2 = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        txtStudentScore2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        selectSemComboBox = new javax.swing.JComboBox<>();
        txtSearchCourses = new javax.swing.JTextField();
        btnSearchCourses = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane12 = new javax.swing.JScrollPane();
        createCoursePanel1 = new javax.swing.JPanel();
        jLabel53 = new javax.swing.JLabel();
        txtCreateCourseId1 = new javax.swing.JTextField();
        jLabel54 = new javax.swing.JLabel();
        txtCreateCourseTopic1 = new javax.swing.JTextField();
        jLabel55 = new javax.swing.JLabel();
        txtCreateCourseName1 = new javax.swing.JTextField();
        jLabel56 = new javax.swing.JLabel();
        txtCreateCoursePoint1 = new javax.swing.JTextField();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        txtCreateCourseLocation1 = new javax.swing.JTextField();
        jLabel59 = new javax.swing.JLabel();
        lblCourseEndTime4 = new javax.swing.JLabel();
        lblStudentLimited4 = new javax.swing.JLabel();
        txtCreateStudentLimited1 = new javax.swing.JTextField();
        jLabel60 = new javax.swing.JLabel();
        txtCreateStudentCount1 = new javax.swing.JTextField();
        jLabel61 = new javax.swing.JLabel();
        jScrollPane13 = new javax.swing.JScrollPane();
        createCourseIntroductionTextArea1 = new javax.swing.JTextArea();
        btnCreate1 = new javax.swing.JButton();
        selectSemComboBox1 = new javax.swing.JComboBox<>();
        cbBeginHour3 = new javax.swing.JComboBox<>();
        cbBeginMinute3 = new javax.swing.JComboBox<>();
        cbEndHour3 = new javax.swing.JComboBox<>();
        cbEndMinute3 = new javax.swing.JComboBox<>();

        mainTabbedPane.setBackground(new java.awt.Color(204, 204, 255));
        mainTabbedPane.setToolTipText("");
        mainTabbedPane.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N

        tblCurrentCourses1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Course ID", "Couse Name", "Course Topic", "Course Location"
            }
        ));
        jScrollPane10.setViewportView(tblCurrentCourses1);

        jLabel40.setText("Course ID:");

        jLabel41.setText("Course Topic:");

        jLabel42.setText("Course Name:");

        jLabel43.setText("Course point:");

        jLabel44.setText("Semester:");

        jLabel45.setText("Course Location:");

        jLabel46.setText("Course Begintime:");

        lblCourseEndTime3.setText("Course Endtime:");

        lblStudentLimited3.setText("Student Limited:");

        jLabel47.setText("Student Count:");

        btnSaveCurrentCourse1.setText("Save");
        btnSaveCurrentCourse1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveCurrentCourse1ActionPerformed(evt);
            }
        });

        jLabel48.setText("Course Introduction");

        currentCourseIntroductionTextArea1.setColumns(20);
        currentCourseIntroductionTextArea1.setRows(5);
        jScrollPane11.setViewportView(currentCourseIntroductionTextArea1);

        cbBeginHour2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0  ", "1  ", "2  ", "3  ", "4  ", "5  ", "6  ", "7  ", "8  ", "9  ", "10  ", "11  ", "12" }));

        cbBeginMinute2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0  ", "1  ", "2  ", "3  ", "4  ", "5  ", "6  ", "7  ", "8  ", "9  ", "10  ", "11  ", "12  ", "13  ", "14  ", "15  ", "16  ", "17  ", "18  ", "19  ", "20  ", "21  ", "22  ", "23  ", "24  ", "25  ", "26  ", "27  ", "28  ", "29  ", "30  ", "31  ", "32  ", "33  ", "34  ", "35  ", "36  ", "37  ", "38  ", "39  ", "40  ", "41  ", "42  ", "43  ", "44  ", "45  ", "46  ", "47  ", "48  ", "49  ", "50  ", "51  ", "52  ", "53  ", "54  ", "55  ", "56  ", "57  ", "58  ", "59  ", "60" }));

        cbEndHour2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0  ", "1  ", "2  ", "3  ", "4  ", "5  ", "6  ", "7  ", "8  ", "9  ", "10  ", "11  ", "12" }));

        cbEndMinute2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0  ", "1  ", "2  ", "3  ", "4  ", "5  ", "6  ", "7  ", "8  ", "9  ", "10  ", "11  ", "12  ", "13  ", "14  ", "15  ", "16  ", "17  ", "18  ", "19  ", "20  ", "21  ", "22  ", "23  ", "24  ", "25  ", "26  ", "27  ", "28  ", "29  ", "30  ", "31  ", "32  ", "33  ", "34  ", "35  ", "36  ", "37  ", "38  ", "39  ", "40  ", "41  ", "42  ", "43  ", "44  ", "45  ", "46  ", "47  ", "48  ", "49  ", "50  ", "51  ", "52  ", "53  ", "54  ", "55  ", "56  ", "57  ", "58  ", "59  ", "60" }));

        jLabel49.setText("Student List");

        tblStudent2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Student Name", "Student NUID", "Student Score"
            }
        ));
        jScrollPane4.setViewportView(tblStudent2);

        btnSearchStudent2.setText("Search");
        btnSearchStudent2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchStudent2ActionPerformed(evt);
            }
        });

        jLabel50.setText("Student Name:");

        jLabel51.setText("Student ID:");

        jLabel52.setText("Student Scores:");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel2.setText("Select Semester:");

        selectSemComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                selectSemComboBoxItemStateChanged(evt);
            }
        });
        selectSemComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectSemComboBoxActionPerformed(evt);
            }
        });

        txtSearchCourses.setToolTipText("");
        txtSearchCourses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchCoursesActionPerformed(evt);
            }
        });

        btnSearchCourses.setText("Search");
        btnSearchCourses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchCoursesActionPerformed(evt);
            }
        });

        jLabel1.setText("ProfessorName/language/Region/CourseName/CouseTopic");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(txtSearchStudent2, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(btnSearchStudent2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(180, 180, 180))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel48)
                            .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(78, 78, 78))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 687, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(txtStudentId2, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(txtStudentName2, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(txtStudentScore2, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(166, 166, 166))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtCurrentCourseId1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel42)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCurrentCourseName1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel41)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCurrentCourseTopic1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel43)
                                    .addComponent(jLabel44))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(txtCurrentSemester1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(txtCurrentCoursePoint1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(106, 106, 106)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCourseEndTime3)
                            .addComponent(jLabel46)
                            .addComponent(lblStudentLimited3)
                            .addComponent(jLabel47)
                            .addComponent(jLabel45))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(txtCurrentStudentCount1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(txtCurrentStudentLimited1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(txtCurrentCourseLocation1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cbEndHour2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbBeginHour2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbBeginMinute2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbEndMinute2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(selectSemComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtSearchCourses, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(btnSearchCourses, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(18, 18, 18))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSaveCurrentCourse1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectSemComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearchCourses, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchCourses, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel40)
                            .addComponent(txtCurrentCourseId1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel41)
                            .addComponent(txtCurrentCourseTopic1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel42)
                            .addComponent(txtCurrentCourseName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel43)
                            .addComponent(txtCurrentCoursePoint1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel44)
                            .addComponent(txtCurrentSemester1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel45)
                            .addComponent(txtCurrentCourseLocation1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel46)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblCourseEndTime3))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbBeginHour2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbBeginMinute2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbEndHour2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbEndMinute2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblStudentLimited3)
                            .addComponent(txtCurrentStudentLimited1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel47)
                            .addComponent(txtCurrentStudentCount1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel48)
                        .addGap(53, 53, 53))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel49))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearchStudent2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchStudent2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel50)
                    .addComponent(txtStudentName2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel51)
                    .addComponent(txtStudentId2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel52)
                    .addComponent(txtStudentScore2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(btnSaveCurrentCourse1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        currentCourseScrollPane1.setViewportView(jPanel2);

        jScrollPane3.setViewportView(currentCourseScrollPane1);

        mainTabbedPane.addTab("Current Course", jScrollPane3);

        jLabel53.setText("Course ID:");

        jLabel54.setText("Course Topic:");

        jLabel55.setText("Course Name:");

        jLabel56.setText("Course point:");

        jLabel57.setText("Semester:");

        jLabel58.setText("Course Location:");

        jLabel59.setText("Course Begintime:");

        lblCourseEndTime4.setText("Course Endtime:");

        lblStudentLimited4.setText("Student Limited:");

        jLabel60.setText("Student Count:");

        jLabel61.setText("Course Introduction");

        createCourseIntroductionTextArea1.setColumns(20);
        createCourseIntroductionTextArea1.setRows(5);
        jScrollPane13.setViewportView(createCourseIntroductionTextArea1);

        btnCreate1.setText("Create");
        btnCreate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreate1ActionPerformed(evt);
            }
        });

        selectSemComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                selectSemComboBox1ItemStateChanged(evt);
            }
        });
        selectSemComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectSemComboBox1ActionPerformed(evt);
            }
        });

        cbBeginHour3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0  ", "1  ", "2  ", "3  ", "4  ", "5  ", "6  ", "7  ", "8  ", "9  ", "10  ", "11  ", "12" }));

        cbBeginMinute3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0  ", "1  ", "2  ", "3  ", "4  ", "5  ", "6  ", "7  ", "8  ", "9  ", "10  ", "11  ", "12  ", "13  ", "14  ", "15  ", "16  ", "17  ", "18  ", "19  ", "20  ", "21  ", "22  ", "23  ", "24  ", "25  ", "26  ", "27  ", "28  ", "29  ", "30  ", "31  ", "32  ", "33  ", "34  ", "35  ", "36  ", "37  ", "38  ", "39  ", "40  ", "41  ", "42  ", "43  ", "44  ", "45  ", "46  ", "47  ", "48  ", "49  ", "50  ", "51  ", "52  ", "53  ", "54  ", "55  ", "56  ", "57  ", "58  ", "59  ", "60" }));

        cbEndHour3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0  ", "1  ", "2  ", "3  ", "4  ", "5  ", "6  ", "7  ", "8  ", "9  ", "10  ", "11  ", "12" }));

        cbEndMinute3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0  ", "1  ", "2  ", "3  ", "4  ", "5  ", "6  ", "7  ", "8  ", "9  ", "10  ", "11  ", "12  ", "13  ", "14  ", "15  ", "16  ", "17  ", "18  ", "19  ", "20  ", "21  ", "22  ", "23  ", "24  ", "25  ", "26  ", "27  ", "28  ", "29  ", "30  ", "31  ", "32  ", "33  ", "34  ", "35  ", "36  ", "37  ", "38  ", "39  ", "40  ", "41  ", "42  ", "43  ", "44  ", "45  ", "46  ", "47  ", "48  ", "49  ", "50  ", "51  ", "52  ", "53  ", "54  ", "55  ", "56  ", "57  ", "58  ", "59  ", "60" }));

        javax.swing.GroupLayout createCoursePanel1Layout = new javax.swing.GroupLayout(createCoursePanel1);
        createCoursePanel1.setLayout(createCoursePanel1Layout);
        createCoursePanel1Layout.setHorizontalGroup(
            createCoursePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createCoursePanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(createCoursePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createCoursePanel1Layout.createSequentialGroup()
                        .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtCreateCourseId1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(createCoursePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, createCoursePanel1Layout.createSequentialGroup()
                            .addComponent(jLabel55)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtCreateCourseName1))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, createCoursePanel1Layout.createSequentialGroup()
                            .addComponent(jLabel54)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtCreateCourseTopic1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, createCoursePanel1Layout.createSequentialGroup()
                            .addGroup(createCoursePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel56)
                                .addComponent(jLabel57))
                            .addGap(17, 17, 17)
                            .addGroup(createCoursePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtCreateCoursePoint1, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                                .addComponent(selectSemComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(106, 106, 106)
                .addGroup(createCoursePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCourseEndTime4)
                    .addComponent(jLabel59)
                    .addComponent(lblStudentLimited4)
                    .addComponent(jLabel60)
                    .addComponent(jLabel58))
                .addGroup(createCoursePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(createCoursePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(createCoursePanel1Layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(txtCreateStudentCount1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(createCoursePanel1Layout.createSequentialGroup()
                            .addGap(5, 5, 5)
                            .addComponent(txtCreateStudentLimited1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createCoursePanel1Layout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addComponent(txtCreateCourseLocation1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(createCoursePanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(createCoursePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbEndHour3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbBeginHour3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(createCoursePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbBeginMinute3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbEndMinute3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(78, Short.MAX_VALUE))
            .addGroup(createCoursePanel1Layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(jLabel61)
                .addGap(38, 38, 38)
                .addComponent(jScrollPane13)
                .addGap(141, 141, 141))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createCoursePanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCreate1)
                .addGap(92, 92, 92))
        );
        createCoursePanel1Layout.setVerticalGroup(
            createCoursePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createCoursePanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(createCoursePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(createCoursePanel1Layout.createSequentialGroup()
                        .addGroup(createCoursePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel53)
                            .addComponent(txtCreateCourseId1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(createCoursePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel54)
                            .addComponent(txtCreateCourseTopic1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(createCoursePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel55)
                            .addComponent(txtCreateCourseName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(createCoursePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel56)
                            .addComponent(txtCreateCoursePoint1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(createCoursePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel57)
                            .addComponent(selectSemComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(createCoursePanel1Layout.createSequentialGroup()
                        .addGroup(createCoursePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel58)
                            .addComponent(txtCreateCourseLocation1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(createCoursePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(createCoursePanel1Layout.createSequentialGroup()
                                .addComponent(jLabel59)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblCourseEndTime4))
                            .addGroup(createCoursePanel1Layout.createSequentialGroup()
                                .addGroup(createCoursePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbBeginHour3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbBeginMinute3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(createCoursePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbEndHour3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbEndMinute3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(createCoursePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblStudentLimited4)
                            .addComponent(txtCreateStudentLimited1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(createCoursePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel60)
                            .addComponent(txtCreateStudentCount1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(createCoursePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(createCoursePanel1Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel61))
                    .addGroup(createCoursePanel1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(92, 92, 92)
                .addComponent(btnCreate1)
                .addContainerGap(513, Short.MAX_VALUE))
        );

        jScrollPane12.setViewportView(createCoursePanel1);

        mainTabbedPane.addTab("CreateCourse", jScrollPane12);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainTabbedPane)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveCurrentCourse1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveCurrentCourse1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveCurrentCourse1ActionPerformed

    private void btnSearchStudent2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchStudent2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchStudent2ActionPerformed

    private void btnCreate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreate1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCreate1ActionPerformed

    private void selectSemComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_selectSemComboBox1ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_selectSemComboBox1ItemStateChanged

    private void selectSemComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectSemComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectSemComboBox1ActionPerformed

    private void selectSemComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_selectSemComboBoxItemStateChanged
        // TODO add your handling code here:
        System.out.println("selectSemComboBox.getSelectedItem().toString():"+selectSemComboBox.getSelectedItem().toString());
        populateTable("",selectSemComboBox.getSelectedItem().toString());

        txtCurrentCourseId.setText("");
        txtCurrentCourseName.setText("");
        txtCurrentCourseTopic.setText("");
        txtCurrentSemester.setText("");
        txtCurrentProfessor.setText("");
        txtCurrentProfessorRegion.setText("");
        txtCurrentCourseLocation.setText("");
        currentCourseIntroductionTextArea.setText("");
        txtCurrentStudentLimited.setText("");
        txtCurrentStudentCount.setText("");
        txtCurrentCoursePoint.setText("");
        txtCurrentCourseStartTime.setText("");
        txtCurrentCourseEndTime.setText("");
        txtCurrentProfessorLanguage.setText("");
    }//GEN-LAST:event_selectSemComboBoxItemStateChanged

    private void selectSemComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectSemComboBoxActionPerformed
        // TODO add your handling code here:
        if(selectSemComboBox.getSelectedItem().toString().equals(thisterm)){
            btnDrop.setVisible(true);
        }else {
            btnDrop.setVisible(false);
        }
        //        populateTable(thisterm);
    }//GEN-LAST:event_selectSemComboBoxActionPerformed

    private void txtSearchCoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchCoursesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchCoursesActionPerformed

    private void btnSearchCoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchCoursesActionPerformed
        // TODO add your handling code here:
        populateTable(txtSearchCourses.getText(),selectSemComboBox.getSelectedItem().toString());

        txtCurrentCourseId.setText("");
        txtCurrentCourseName.setText("");
        txtCurrentCourseTopic.setText("");
        txtCurrentSemester.setText("");
        txtCurrentProfessor.setText("");
        txtCurrentProfessorRegion.setText("");
        txtCurrentCourseLocation.setText("");
        currentCourseIntroductionTextArea.setText("");
        txtCurrentStudentLimited.setText("");
        txtCurrentStudentCount.setText("");
        txtCurrentCoursePoint.setText("");
        txtCurrentCourseStartTime.setText("");
        txtCurrentCourseEndTime.setText("");
        txtCurrentProfessorLanguage.setText("");
    }//GEN-LAST:event_btnSearchCoursesActionPerformed


    private void populateTable(String semester) {
        DefaultTableModel model = (DefaultTableModel) tblCurrentCourses.getModel(); //Have the access to the table;
        model.setRowCount(0); //初始化
        professsorCourseList = getCreateCourses("",semester);

        for(CourseVO course : professsorCourseList){

            Object[] row = new Object[4];
            row[0] = course.getId();
            row[1] = course.getName();
            row[2] = course.getTopics();
            row[3] = course.getLocation();

            //设置3R对应

            model.addRow(row);

        }
    }

    public List<CourseVO> getCreateCourses(String keyWords,String semester){
        List<CourseVO>  professsorCourseList = new ArrayList<>();
        try {
             professsorCourseList = courseDirectory.loadCourseListByProfessorIdFromDatabase(keyWords,professor.getPersonID(),semester);
            return professsorCourseList;
        } catch (SQLException e) {
            e.printStackTrace();
            System.out.println("Database is not work");
        }
        return professsorCourseList;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate1;
    private javax.swing.JButton btnSaveCurrentCourse1;
    private javax.swing.JButton btnSearchCourses;
    private javax.swing.JButton btnSearchStudent2;
    private javax.swing.JComboBox<String> cbBeginHour2;
    private javax.swing.JComboBox<String> cbBeginHour3;
    private javax.swing.JComboBox<String> cbBeginMinute2;
    private javax.swing.JComboBox<String> cbBeginMinute3;
    private javax.swing.JComboBox<String> cbEndHour2;
    private javax.swing.JComboBox<String> cbEndHour3;
    private javax.swing.JComboBox<String> cbEndMinute2;
    private javax.swing.JComboBox<String> cbEndMinute3;
    private javax.swing.JTextArea createCourseIntroductionTextArea1;
    private javax.swing.JPanel createCoursePanel1;
    private javax.swing.JTextArea currentCourseIntroductionTextArea1;
    private javax.swing.JScrollPane currentCourseScrollPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblCourseEndTime3;
    private javax.swing.JLabel lblCourseEndTime4;
    private javax.swing.JLabel lblStudentLimited3;
    private javax.swing.JLabel lblStudentLimited4;
    private javax.swing.JTabbedPane mainTabbedPane;
    private javax.swing.JComboBox<String> selectSemComboBox;
    private javax.swing.JComboBox<String> selectSemComboBox1;
    private javax.swing.JTable tblCurrentCourses1;
    private javax.swing.JTable tblStudent2;
    private javax.swing.JTextField txtCreateCourseId1;
    private javax.swing.JTextField txtCreateCourseLocation1;
    private javax.swing.JTextField txtCreateCourseName1;
    private javax.swing.JTextField txtCreateCoursePoint1;
    private javax.swing.JTextField txtCreateCourseTopic1;
    private javax.swing.JTextField txtCreateStudentCount1;
    private javax.swing.JTextField txtCreateStudentLimited1;
    private javax.swing.JTextField txtCurrentCourseId1;
    private javax.swing.JTextField txtCurrentCourseLocation1;
    private javax.swing.JTextField txtCurrentCourseName1;
    private javax.swing.JTextField txtCurrentCoursePoint1;
    private javax.swing.JTextField txtCurrentCourseTopic1;
    private javax.swing.JTextField txtCurrentSemester1;
    private javax.swing.JTextField txtCurrentStudentCount1;
    private javax.swing.JTextField txtCurrentStudentLimited1;
    private javax.swing.JTextField txtSearchCourses;
    private javax.swing.JTextField txtSearchStudent2;
    private javax.swing.JTextField txtStudentId2;
    private javax.swing.JTextField txtStudentName2;
    private javax.swing.JTextField txtStudentScore2;
    // End of variables declaration//GEN-END:variables
}
