package ui;

import java.awt.CardLayout;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

import Business.Directory.EmployeeDirectory;
import Business.Directory.StudentDirectory;
import Business.Person.Employee;
import Business.Person.Professor;
import Business.Person.Student;
import Tools.MySQLConnectionUtil;
import Business.Directory.ProfessorDirectory;
import ui.UserInterface.WorkAreas.AdminRole.AdminWorkAreaJPanel;
import ui.UserInterface.WorkAreas.FacultyRole.FacultyWorkAreaJPanel;
import ui.UserInterface.WorkAreas.StudentRole.StudentWorkAreaJPanel;

/**
 *
 * @author freax
 */


public class LoginJPanel extends javax.swing.JPanel {
    int i=0;
    private JPanel ViewContainer;
    private JPanel controlPanel;

    Connection connection = MySQLConnectionUtil.getConnection();
    public LoginJPanel(JPanel ViewContainer,  JPanel controlPanel) {
        initComponents();
        this.ViewContainer = ViewContainer;
        this.controlPanel = controlPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        loginbtn = new javax.swing.JButton();
        lbltitle = new javax.swing.JLabel();
        txtloginusername = new javax.swing.JTextField();
        lblusername = new javax.swing.JLabel();
        lblpwd = new javax.swing.JLabel();
        txtloginpwd = new javax.swing.JPasswordField();
        btnAdmin = new javax.swing.JRadioButton();
        btnProfessor = new javax.swing.JRadioButton();
        btnStudent = new javax.swing.JRadioButton();
        register = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginbtn.setText("Login");
        loginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    loginbtnActionPerformed(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        });
        add(loginbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 271, 78, -1));

        lbltitle.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lbltitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltitle.setText("Login in");
        add(lbltitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 18, 561, -1));

        txtloginusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtloginusernameActionPerformed(evt);
            }
        });
        add(txtloginusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 110, 165, -1));

        lblusername.setText("User Name:");
        add(lblusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 113, -1, -1));

        lblpwd.setText("Password:");
        add(lblpwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 167, -1, -1));
        add(txtloginpwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 164, 165, -1));

        buttonGroup1.add(btnAdmin);
        btnAdmin.setText("Admin");

        add(btnAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 213, -1, -1));

        buttonGroup1.add(btnProfessor);
        btnProfessor.setText("Faculty");

        add(btnProfessor, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 213, -1, -1));

        buttonGroup1.add(btnStudent);
        btnStudent.setText("Student");

        add(btnStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 213, -1, -1));

        register.setText("Register");
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });
        add(register, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 321, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void loginbtnActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {
        String username = txtloginusername.getText();
        String password = Arrays.toString(txtloginpwd.getPassword());
        connection =  MySQLConnectionUtil.getConnection();
        // 调用 Employee、Professor、Student 中的身份验证方法
        boolean loginSuccess = false;
        if (btnAdmin.isSelected()) {

            System.out.println("admin");
            loginSuccess = Tools.PasswordUtils.verifyLogin(connection, username, password, "Employee");

        } else if (btnProfessor.isSelected()) {
            System.out.println("professor");
            loginSuccess = Tools.PasswordUtils.verifyLogin(connection, username, password, "Professor");

        } else if (btnStudent.isSelected()) {
            System.out.println("student");
            loginSuccess = Tools.PasswordUtils.verifyLogin(connection, username, password, "Student");

        }

        if (loginSuccess) {
            // 根据用户身份切换到不同的界面
            if (btnAdmin.isSelected()) {
                JOptionPane.showMessageDialog(this, "Succuss!");

                EmployeeDirectory adminlist = new EmployeeDirectory();
                Employee employee = adminlist.findEmployeeByUsername(username);

                AdminWorkAreaJPanel admincontrolpanel = new AdminWorkAreaJPanel(ViewContainer, controlPanel,employee);
                controlPanel.add(admincontrolpanel);
                CardLayout layout1 = (CardLayout)controlPanel.getLayout();
                layout1.next(controlPanel);


                JPanel panel = new JPanel();
                ViewContainer.add("Block",panel);
                CardLayout layout = (CardLayout)ViewContainer.getLayout();
                layout.next(ViewContainer);
                // 显示 Employee 界面
            } else if (btnProfessor.isSelected()) {
                // 显示 Professor 界面
                JOptionPane.showMessageDialog(this, "Succuss!");
                ProfessorDirectory professorDirectory = new ProfessorDirectory();
                professorDirectory.loadAllProfessorsFromDatabase(connection);
                Professor professor = professorDirectory.getProfessorByusername(username);

                FacultyWorkAreaJPanel panel1 = new FacultyWorkAreaJPanel( ViewContainer, controlPanel,  professor);
                controlPanel.add(panel1);
                CardLayout layout1 = (CardLayout)controlPanel.getLayout();
                layout1.next(controlPanel);

                JPanel panel = new JPanel();
                ViewContainer.add("Block",panel);
                CardLayout layout = (CardLayout)ViewContainer.getLayout();
                layout.next(ViewContainer);
            } else if (btnStudent.isSelected()) {
                // 显示 Student 界面
                JOptionPane.showMessageDialog(this, "Succuss!");

                StudentDirectory stulist = new StudentDirectory();
                Student student = stulist.findStudentbyUsername(username);
                StudentWorkAreaJPanel panel1 = new StudentWorkAreaJPanel(ViewContainer, controlPanel, student);
                controlPanel.add(panel1);
                CardLayout layout1 = (CardLayout)controlPanel.getLayout();
                layout1.next(controlPanel);


                JPanel panel = new JPanel();
                ViewContainer.add("Block",panel);
                CardLayout layout = (CardLayout)ViewContainer.getLayout();
                layout.next(ViewContainer);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Login failed. Please check your credentials.");
        }


    }
    private void txtloginusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtloginusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtloginusernameActionPerformed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed

        validationJPanel panel = new validationJPanel(ViewContainer,controlPanel);
        ViewContainer.add("validationJPanel",panel);
        CardLayout layout = (CardLayout)ViewContainer.getLayout();
        layout.next(ViewContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_registerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnAdmin;
    private javax.swing.JRadioButton btnProfessor;
    private javax.swing.JRadioButton btnStudent;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel lblpwd;
    private javax.swing.JLabel lbltitle;
    private javax.swing.JLabel lblusername;
    private javax.swing.JButton loginbtn;
    private javax.swing.JButton register;
    private javax.swing.JPasswordField txtloginpwd;
    private javax.swing.JTextField txtloginusername;
    // End of variables declaration//GEN-END:variables
}
