/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.CardLayout;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.PersonList;
import model.Person;
import model.User;
import ui.UserInterface.WorkAreas.AdminRole.AdminWorkAreaJPanel;

/**
 *
 * @author freax
 */


public class LoginJPanel extends javax.swing.JPanel {

    private JPanel ViewContainer;
    private PersonList personList;
    private JPanel controlPanel;

    public LoginJPanel(JPanel ViewContainer, PersonList personList, JPanel controlPanel) {
        initComponents();
        this.ViewContainer = ViewContainer;
        this.personList = personList;
        this.controlPanel = controlPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginbtn = new javax.swing.JButton();
        lbltitle = new javax.swing.JLabel();
        txtloginusername = new javax.swing.JTextField();
        lblusername = new javax.swing.JLabel();
        lblpwd = new javax.swing.JLabel();
        txtloginpwd = new javax.swing.JPasswordField();

        loginbtn.setText("Login");
        loginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbtnActionPerformed(evt);
            }
        });

        lbltitle.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lbltitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltitle.setText("Login in");

        txtloginusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtloginusernameActionPerformed(evt);
            }
        });

        lblusername.setText("User Name:");

        lblpwd.setText("Password:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbltitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(163, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblpwd)
                    .addComponent(lblusername))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loginbtn)
                    .addComponent(txtloginusername, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtloginpwd, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(158, 158, 158))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lbltitle)
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtloginusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblusername))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblpwd)
                    .addComponent(txtloginpwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(loginbtn)
                .addContainerGap(117, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void loginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbtnActionPerformed
        String username = txtloginusername.getText();
        String pwd = new String(txtloginpwd.getPassword());

        
        try{
            if (isValidUser(username, pwd).getRole().equals("admin")&&isValidUser(username, pwd).isEnabled()) {
                JOptionPane.showMessageDialog(this, "Succuss!");
                AdminWorkAreaJPanel panel1 = new AdminWorkAreaJPanel( ViewContainer, controlPanel,  personList);
                controlPanel.add(panel1);
                CardLayout layout1 = (CardLayout)controlPanel.getLayout();
                layout1.next(controlPanel);
                User user = isValidUser(username, pwd);
                AdminJPanel panel = new AdminJPanel(ViewContainer,personList,user);
                ViewContainer.add("AdminJPanel",panel);
                CardLayout layout = (CardLayout)ViewContainer.getLayout();
                layout.next(ViewContainer);
            } else if (isValidUser(username, pwd).getRole().equals("user")&&isValidUser(username, pwd).isEnabled()) {
                JOptionPane.showMessageDialog(this, "Succuss!");

                User user = isValidUser(username, pwd);
                UserViewPanel panel = new UserViewPanel(ViewContainer,personList,user);
                ViewContainer.add("UserViewPanel",panel);
                CardLayout layout = (CardLayout)ViewContainer.getLayout();
                layout.next(ViewContainer);
            }else if(!isValidUser(username, pwd).isEnabled()){
                JOptionPane.showMessageDialog(this, "Account unavailable! Please contact admin!");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Wrong Username/Wrong Password");
        }

    }//GEN-LAST:event_loginbtnActionPerformed

    private User isValidUser(String username, String password) {
        Person p = personList.searchPersonByusername(username);
        ArrayList<User> users = p.getUsers();
        for (User user : users) {
          
            if (user.getUsername().equals(username)
                    && user.validatePassword(password)) {
                
                return user;
            }
        }
        return null;
    }
    private void txtloginusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtloginusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtloginusernameActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblpwd;
    private javax.swing.JLabel lbltitle;
    private javax.swing.JLabel lblusername;
    private javax.swing.JButton loginbtn;
    private javax.swing.JPasswordField txtloginpwd;
    private javax.swing.JTextField txtloginusername;
    // End of variables declaration//GEN-END:variables
}
