/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.PersonList;
import model.User;
import model.Person;
import ui.MainJFrame;
import static ui.MainJFrame.writeDataToFile;
/**
 *
 * @author freax
 */
public class UserViewPanel extends javax.swing.JPanel {

    /**
     * Creates new form UserViewPanel
     */
    private JPanel ViewContainer;
    private PersonList personList;
    private User user;
    UserViewPanel(JPanel ViewContainer, PersonList personList,User user) {
        initComponents();
        this.ViewContainer = ViewContainer;
        this.personList = personList;
        this.user = user;
        
        Person p = personList.searchPersonByusername(user.getUsername());
        txtNUID.setText(p.getNUID());
        txtCharactor.setText(user.getRole());
        txtName.setText(p.getName());
        txtUserName.setText(user.getUsername());
        txtNUID.setEditable(false);
        txtName.setEditable(false);
        txtUserName.setEditable(false);
        btnSave.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblviewprofiletitle = new javax.swing.JLabel();
        lblNUID = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblCharactor = new javax.swing.JLabel();
        txtNUID = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtUserName = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        txtCharactor = new javax.swing.JLabel();
        btnuseredit = new javax.swing.JButton();
        txtpwd = new javax.swing.JTextField();

        lblviewprofiletitle.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        lblviewprofiletitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblviewprofiletitle.setText("View Profile");

        lblNUID.setText("NUID");

        lblName.setText("Name");

        lblUsername.setText("User Name");

        lblCharactor.setText("Charactor");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnuseredit.setText("change password");
        btnuseredit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnusereditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblviewprofiletitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblCharactor)
                                    .addComponent(lblName)
                                    .addComponent(lblNUID)
                                    .addComponent(lblUsername))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNUID, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCharactor)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtpwd, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnSave)
                                    .addGap(60, 60, 60)
                                    .addComponent(btnEdit))))
                        .addGap(0, 91, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnuseredit, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblviewprofiletitle, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNUID)
                    .addComponent(txtNUID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblName))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCharactor)
                    .addComponent(txtCharactor))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnEdit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(txtpwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnuseredit)
                .addGap(23, 23, 23))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        Person p = personList.searchPersonByusername(user.getUsername());
        p.setNUID(txtNUID.getText());
        p.setName(txtName.getText());
        p.getUserbyName(user.getUsername()).setUsername(txtUserName.getText());
        
        writeDataToFile(personList, "personlist.txt");
        txtNUID.setEditable(false);
        txtName.setEditable(false);
        txtUserName.setEditable(false);
        btnSave.setVisible(false);
        btnEdit.setVisible(true);
        PersonList personList = MainJFrame.readDataFromFile("personlist.txt");
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        txtNUID.setEditable(true);
        txtName.setEditable(true);
        txtUserName.setEditable(true);
        btnSave.setVisible(true);
        btnEdit.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnusereditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnusereditActionPerformed
        if(txtpwd.getText()==""){
            JOptionPane.showMessageDialog(this, "Please enter new password.");
        }
        Person p = personList.searchPersonByusername(user.getUsername());
        if(user.setNowpwd(user.hashPassword(txtpwd.getText()))){
            JOptionPane.showMessageDialog(this, "Success");
            writeDataToFile(personList, "personlist.txt");
        }else{
            JOptionPane.showMessageDialog(this, "Please not use history password.");
        }
        
    }//GEN-LAST:event_btnusereditActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnuseredit;
    private javax.swing.JLabel lblCharactor;
    private javax.swing.JLabel lblNUID;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblviewprofiletitle;
    private javax.swing.JLabel txtCharactor;
    private javax.swing.JTextField txtNUID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtUserName;
    private javax.swing.JTextField txtpwd;
    // End of variables declaration//GEN-END:variables
}
